language: php

sudo: false

php:
    - 5.5
    - 5.6
    - 7.0

before_script:
    - phpenv config-rm xdebug.ini
    - travis_retry composer self-update
    - travis_retry composer update --no-interaction --profile --verbose

script:
    - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)