language: php

sudo: false

php:
    - 5.5
    - 5.6
    - 7.0

## Cache composer bits 
cache: 
  directories: 
    - $HOME/.composer/cache

before_script:
    - travis_retry composer self-update
    - travis_retry composer update --no-interaction

script:
    - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)

matrix:
  allow_failures:
    - php: 7.0
  fast_finish: true