language: php

sudo: false

php:
    - 7.0
    - 7.1
    - 7.2

cache:
  directories:
    - $HOME/.composer/cache

before_script:
    - travis_retry composer self-update
    - travis_retry composer update --no-interaction

script:
    - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)
